server:
  port: ${PORT:8081}
spring:



  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456
    initialize: true
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  sql:
    init:
      continue-on-error: true
      mode: always
      platform: postgresql

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app-config:

  services:
    sales:  http://${SALES_HOST:localhost}:${SALES_PORT:8082}

  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LTEyMzQ1NTY=}

  rabbit:
    exchange:
      product: product.topic

    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue